#!/usr/bin/env python
# vim: set expandtab ts=4 sw=4:

# cloud_status - tool to display information about cloud scheduler
# 
# Patrick Armstrong at UVic, 2009
import xmlrpclib
import cloud_management
import sys
import socket

# Server variables
server_hostname = "localhost"
server_port = "8000"

try:
    s = xmlrpclib.ServerProxy("http://%s:%s" % (server_hostname, server_port))
    print s.get_cloud_resources()
except socket.error:
    print "%s: couldn't connect to cloud scheduler at %s on port %s."\
           % (sys.argv[0], server_hostname, server_port)
    print "Is the cloud scheduler running?"
except:
    print "Unexpected error: ", sys.exc_info()[0]
