#!/usr/bin/env python
import xmlrpclib
import cloud_management

s = xmlrpclib.ServerProxy('http://localhost:8000')

print s.get_cloud_resources()

# Print list of available methods
print s.system.listMethods()

