#!/bin/sh
#
# chkconfig:    345 85 15
# description:  Cloud Scheduler init script for GNU/Linux

export GLOBUS_LOCATION=/usr/local/nimbus/

# Set a non-default path to the cloud_scheduler executable
# eg. "/opt/bin/cloud_scheduler"
EXECUTABLEPATH="cloud_scheduler" 

# Non-default python (eg. if you installed python 2.6 on RHEL5)
PYTHON="python"

# You probably won't want to change these.
SERVICE=cloud_scheduler
PIDSPATH=/var/run
PIDFILE=$PIDSPATH/$SERVICE.pid
export PATH=$PATH:$GLOBUS_LOCATION/bin/

start () {
    if [ ! -f $PIDFILE ]; then
        echo -n $"Starting $SERVICE..."
        if [ "$SUDO_COMMAND" ]; then
            sudo nohup ${PYTHON} ${EXECUTABLEPATH} </dev/null >/dev/null &
            echo $! > $PIDFILE
        else
            nohup ${PYTHON} ${EXECUTABLEPATH} </dev/null >/dev/null &
            echo $! > $PIDFILE
        fi
        echo
        RETVAL=$?
        touch /var/lock/subsys/$SERVICE
    else
        echo $"$SERVICE is already running. If this is wrong, delete $PIDFILE."
    fi
}

stop () {
    if [ -f $PIDFILE ]; then
        echo -n $"Stopping $SERVICE..."
        kill `cat $PIDFILE`
        echo
        if [ $? -eq 0 ]; then
            rm -f $PIDFILE >/dev/null 2>&1
        fi
        rm -f /var/lock/subsys/$SERVICE
    fi
}

reconfig () {
    if [ -f $PIDFILE ]; then
        echo -n $"Reconfiguring $SERVICE..."
        /bin/kill -s SIGUSR1 `cat $PIDFILE`
        echo
    fi
}

RETVAL=0

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    reconfig)
        reconfig
        ;;
    status)
	if [ -f $PIDFILE ]; then
		echo "$SERVICE is running."
	else
		echo "$SERVICE isn't running."
	fi
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 3
        ;;
esac

exit $RETVAL
