#!/bin/sh
#
# script to add user with full sudo privs

if [ $USER != "root" ]; then
    echo "This script needs to be run as root."
    exit 1
fi

#check arguments
if [ $# -ne 2 ]; then

    echo "Usage: `basename $0` newuser ssh-pubkey"
    exit 1
fi

echo "WARNING: THIS SCRIPT WILL CREATE A USER WITH ROOT PRIVILEGES."
echo -n "Are you sure you want to do this [Y/n]:"
read -e CONTINUE
if [ $CONTINUE != "Y" ]; then
    exit 1
fi


NEWUSER=$1
SSHPUB=$2

useradd $NEWUSER
passwd $NEWUSER
su $NEWUSER -c "mkdir ~/.ssh"
su $NEWUSER -c "chmod 700 ~/.ssh"
su $NEWUSER -c "echo ${SSHPUB} > ~/.ssh/authorized_keys"
su $NEWUSER -c "chmod 600 ~/.ssh/authorized_keys"
echo "${NEWUSER}	ALL=(ALL)	ALL" >> /etc/sudoers
chage -d 0 $NEWUSER
